# Generated by Django 5.0.2 on 2024-02-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image1', models.ImageField(upload_to='original/')),
                ('original_image2', models.ImageField(upload_to='original/')),
                ('black_and_white_image', models.ImageField(blank=True, null=True, upload_to='blackAndWhite/')),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to='resize/')),
                ('grayscale_image', models.ImageField(blank=True, null=True, upload_to='grayscale/')),
                ('merged_image', models.ImageField(blank=True, null=True, upload_to='merged/')),
            ],
        ),
    ]
