# Generated by Django 5.0.2 on 2024-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_hp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='black_and_white_image',
            new_name='black_and_white_image1',
        ),
        migrations.RenameField(
            model_name='imagemodel',
            old_name='grayscale_image',
            new_name='grayscale_image1',
        ),
        migrations.RenameField(
            model_name='imagemodel',
            old_name='resized_image',
            new_name='resized_image1',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='black_and_white_image2',
            field=models.ImageField(blank=True, null=True, upload_to='blackAndWhite/'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='grayscale_image2',
            field=models.ImageField(blank=True, null=True, upload_to='grayscale/'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='resized_image2',
            field=models.ImageField(blank=True, null=True, upload_to='resize/'),
        ),
    ]
