# Generated by Django 5.0.2 on 2024-02-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_hp', '0002_imagemodel_grayscale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='aligned_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/aligned/'),
        ),
    ]
