# Generated by Django 5.0.2 on 2024-02-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_hp', '0002_rename_black_and_white_image_imagemodel_black_and_white_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='resized_image1',
            field=models.ImageField(blank=True, null=True, upload_to='resized/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='resized_image2',
            field=models.ImageField(blank=True, null=True, upload_to='resized/'),
        ),
    ]
