# Generated by Django 5.0.1 on 2024-02-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_hp', '0003_alter_imagemodel_resized_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='alignment_image',
            field=models.ImageField(blank=True, null=True, upload_to='alignment/'),
        ),
    ]
