# Generated by Django 5.0.2 on 2024-02-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm_hp', '0003_imagemodel_aligned_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='aligned_image',
        ),
    ]
