# Generated by Django 5.0.1 on 2024-02-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_hp', '0004_imagemodel_alignment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='gif_image',
            field=models.ImageField(blank=True, null=True, upload_to='gif/'),
        ),
    ]
